---
# tasks file for revert
- name: getting current snapshots for revert
  ansible.builtin.command:
    cmd: 'virsh snapshot-list --domain "{{ vm_name }}"'
  changed_when: false
  register: vm_list
  become: '{{ for_root_user }}'

- name: setting last snapshot variable
  ansible.builtin.set_fact:
    last_snapshot: '{{ (vm_list.stdout_lines | last | split(" ")).1 }}'

- name: reverting kali vm to last snapshot
  ansible.builtin.command:
    cmd: 'virsh snapshot-revert --domain "{{ vm_name }}" --snapshotname "{{ last_snapshot }}"'
  register: cmd_output
  changed_when: cmd_output.rc == 0
  become: '{{ for_root_user }}'

- name: deleting last snapshot
  ansible.builtin.command:
    cmd: 'virsh snapshot-delete --domain "{{ vm_name }}" --snapshotname "{{ last_snapshot }}"'
  register: cmd_output
  changed_when: '"deleted" in cmd_output.stdout'
  become: '{{ for_root_user }}'

- name: getting kali back up
  ansible.builtin.include_role:
    name: elreydetoda.cracking_server.vagrant_ctl
  vars:
    vagrant_action: 'start'
