---
# tasks file for vagrant_ctl
- name: checking for stopping
  block:

    - name: stopping vm
      ansible.builtin.command:
        chdir: '{{ vagrant_vm_dir }}'
        cmd: vagrant halt --machine-readable --no-tty
      register: cmd_output
      changed_when: "'Halting domain...' in cmd_output.stdout"
      become: '{{ for_root_user }}'

  when: vagrant_action == 'stop'

- name: checking for starting
  block:

    - name: starting vm
      ansible.builtin.command:
        chdir: '{{ vagrant_vm_dir }}'
        cmd: vagrant up --machine-readable --no-tty
      register: cmd_output
      changed_when: "'Starting domain.' in cmd_output.stdout"
      become: '{{ for_root_user }}'

  when: vagrant_action == 'start'

- name: Destroying vm
  block:

    - name: destroying VM
      ansible.builtin.command:
        chdir: '{{ vagrant_vm_dir }}'
        cmd: vagrant destroy --force --machine-readable --no-tty
      register: cmd_output
      changed_when: "'Removing domain...' in cmd_output.stdout"
      become: '{{ for_root_user }}'

  when: vagrant_action == 'destroy'
  
- name: Re-creating vm
  block:

    - name: destroying VM
      ansible.builtin.command:
        chdir: '{{ vagrant_vm_dir }}'
        cmd: vagrant destroy --force --machine-readable --no-tty
      register: cmd_output
      changed_when: "'Removing domain...' in cmd_output.stdout"
      become: '{{ for_root_user }}'

    - name: starting vm
      ansible.builtin.command:
        chdir: '{{ vagrant_vm_dir }}'
        cmd: vagrant up --machine-readable --no-tty
      register: cmd_output
      changed_when: "'Starting domain.' in cmd_output.stdout"
      become: '{{ for_root_user }}'

  when: vagrant_action == 'recreate'
  
- name: check for update
  block:

    - name: Updating VM base box
      ansible.builtin.command:
        chdir: '{{ vagrant_vm_dir }}'
        cmd: vagrant box update --machine-readable --no-tty
      register: cmd_output
      changed_when: "'Updating' in cmd_output.stdout"
      become: '{{ for_root_user }}'

  when: vagrant_action == 'update'
